#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## launch terminal with alt config

CONFIG="$HOME/.config/hypr/foot/foot.ini"

if [ "$1" == "-f" ]; then
	kitty --app-id='kitty-float' --config="$CONFIG"
elif [ "$1" == "-F" ]; then
	kitty --fullscreen --app-id='kitty-full' --font="Iosevka Nerd Font:size=14" --override=pad=35x35 --config="$CONFIG"
elif [ "$1" == "-s" ]; then
	kitty --app-id='foot-float' --config="$CONFIG" \
	--window-size-pixels=$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2 -f "%wx%h")
else
	kitty 
fi
